### ISSUE TITLE
Add alias to .zshrc file

### ISSUE THREAD

**Issue by mkpt** [Abstrys/dhop#4]
Hi Eron,

Dhop was giving me a "Command not found" error at the command line when I ran dhop help after following these instructions. To get this running on my virt, I had to add the alias specified in the instructions to my .zshrc file in addition to the bash, bash_profile, and bashrc files. Not sure if that's specific to my machine or just Linux, but I thought you should know. Works great now! Thanks!

**Comment by EronHennessey** [comment]
It looks like your virtual machine uses [zsh](http://zsh.sourceforge.net/) instead of [bash](http://www.gnu.org/software/bash/).

You should only need to set it there on that system, none of the `.bash*` files will have anything to do with `zsh`. I'll add a note to the instructions for users of `zsh`.
